global:
message: Welcome to microservice project
logging:
  level:
    root: INFO  
    management:
  endpoints:
    web:
      exposure:
        include: "*"
        endpoint:
    health:
      show-details: always  
