global:
  message: Welcome to the customer service environment

server:
  port: 8082

message: Hello from developer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: pranav

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
